// frontend-angular/src/app/address/address.component.ts
import { Component, Input } from '@angular/core';
import countriesData from './countries';
import { FormGroup } from '@angular/forms';

@Component({
  selector: 'app-address',
  templateUrl: './address.component.html',
  styleUrls: ['./address.component.css'],
})
export class AddressComponent {
  @Input() addressComponents!: FormGroup;
  countries: { name: string; code: string }[];
  constructor() {
    this.countries = [];
    
    Object.keys(countriesData).map((k) =>
      this.countries.push({
        name: (countriesData as any)[k] as any,
        code: k,
      })
    );
  }

  getValue(field: any): any {
    return (this.addressComponents.value as any)[field] ?? '';
  }
  handleChange(event: any, key: string) {
    this.addressComponents.get(key)?.patchValue(event.target.value);
  }
  getHelperText(field: string): string {
    switch (field) {
      case 'country':
        return 'ISO 3166 country code (e.g., US, CA, GB)';
      case 'city':
        return 'Full city name (e.g., San Francisco)';
      case 'state':
        return 'State or province (e.g., CA, NY, ON)';
      case 'zip':
        return 'ZIP or postal code (e.g., 94104)';
      case 'street1':
        return 'First line of the address (e.g., 417 Montgomery Street)';
      case 'street2':
        return 'Second line of the address (e.g., Floor 5)';
      case 'name':
        return 'Name of attention, if person (e.g., Hiro Protagonist)';
      case 'phone':
        return 'Phone number to reach the person or organization (e.g., 415-123-4567)';
      case 'email':
        return 'Email to reach the person or organization (e.g., example@example.com)';
      default:
        return '';
    }
  }
}

<div class="address-container">
    <div *ngFor="let field of ['country', 'city', 'state', 'zip', 'street1', 'street2', 'name', 'phone', 'email']">
      <mat-form-field class="address-input" *ngIf="field !== 'country'">
        <mat-label>{{ field | titlecase }}</mat-label>
        <input
          matInput
          [value]="getValue(field)"
          (input)="handleChange($event, field)"
          [required]="field === 'phone'"
        />
        <mat-hint>{{ getHelperText(field) }}</mat-hint>
      </mat-form-field>
      <mat-form-field class="address-input" *ngIf="field === 'country'">
        <mat-label>Country</mat-label>
        <mat-select
          [value]="getValue(field)"
          (selectionChange)="handleChange($event, field)"
          [required]="true"
        >
          <mat-option *ngFor="let country of countries" [value]="country.code">{{ country.name }}</mat-option>
        </mat-select>
        <mat-hint>{{ getHelperText(field) }}</mat-hint>
      </mat-form-field>
    </div>
  </div>

// frontend-react/src/components/Address.jsx
import React from "react";
import { Grid, MenuItem, TextField } from "@mui/material";
import countries from "../ISO3166-1.alpha2.json";

const Address = ({ addressComponents, handleAddressComponentsChange }) => {
  const { country, city, state, zip, street1, street2, name, phone, email } =
    addressComponents;

  return (
    <Grid container spacing={2}>
      <Grid item xs={6} md={4}>
        <TextField
          select
          label="Country"
          fullWidth
          value={country}
          onChange={(e) =>
            handleAddressComponentsChange({ country: e.target.value })
          }
          required
          helperText="ISO 3166 country code (e.g., US, CA, GB)"
        >
          {Object.keys(countries).map((countryCode) => (
            <MenuItem key={countryCode} value={countryCode}>
              {countries[countryCode]}
            </MenuItem>
          ))}
        </TextField>
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="City"
          fullWidth
          value={city}
          onChange={(e) =>
            handleAddressComponentsChange({ city: e.target.value })
          }
          required
          helperText="Full city name (e.g., San Francisco)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="State"
          fullWidth
          value={state}
          onChange={(e) =>
            handleAddressComponentsChange({ state: e.target.value })
          }
          required
          helperText="State or province (e.g., CA, NY, ON)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="ZIP"
          fullWidth
          value={zip}
          onChange={(e) =>
            handleAddressComponentsChange({ zip: e.target.value })
          }
          required
          helperText="ZIP or postal code (e.g., 94104)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="Street 1"
          fullWidth
          value={street1}
          onChange={(e) =>
            handleAddressComponentsChange({ street1: e.target.value })
          }
          required
          helperText="First line of the address (e.g., 417 Montgomery Street)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="Street 2"
          fullWidth
          value={street2}
          onChange={(e) =>
            handleAddressComponentsChange({ street2: e.target.value })
          }
          helperText="Second line of the address (e.g., Floor 5)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="Name"
          fullWidth
          value={name}
          onChange={(e) =>
            handleAddressComponentsChange({ name: e.target.value })
          }
          helperText="Name of attention, if person (e.g., Hiro Protagonist)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="Phone"
          fullWidth
          value={phone}
          onChange={(e) =>
            handleAddressComponentsChange({ phone: e.target.value })
          }
          required
          helperText="Phone number to reach the person or organization (e.g., 415-123-4567)"
        />
      </Grid>
      <Grid item xs={6} md={4}>
        <TextField
          label="Email"
          fullWidth
          value={email}
          onChange={(e) =>
            handleAddressComponentsChange({ email: e.target.value })
          }
          helperText="Email to reach the person or organization (e.g., example@example.com)"
        />
      </Grid>
    </Grid>
  );
};

export default Address;
