// frontend-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  shipmentForm!: FormGroup;
  rates: any[] = [];
  isLoading = false;

  constructor(private formBuilder: FormBuilder) {
    this.shipmentForm = this.formBuilder.group({
      // From Address
      fromAddress: this.formBuilder.group({
        country: ['US', Validators.required],
        city: ['San Francisco', Validators.required],
        state: ['CA', Validators.required],
        zip: ['94104', Validators.required],
        street1: ['417 Montgomery St', Validators.required],
        street2: ['Floor 5'],
        name: ['Hiro Protagonist'],
        phone: ['415-123-4567', Validators.required],
        email: ['example@example.com'],
      }),

      // To Address
      toAddress: this.formBuilder.group({
        country: ['US', Validators.required],
        city: ['New York', Validators.required],
        state: ['NY', Validators.required],
        zip: ['10001', Validators.required],
        street1: ['123 Broadway', Validators.required],
        name: ['John Doe'],
        phone: ['212-555-7890', Validators.required],
      }),

      // Parcel
      parcel: this.formBuilder.group({
        length: [null, Validators.required],
        width: [null, Validators.required],
        height: [null, Validators.required],
        weight: [null, Validators.required],
      }),
    });
  }
  get toAddress(): FormGroup {
    return this.shipmentForm.get('toAddress') as FormGroup;
  }
  get fromAddress(): FormGroup {
    return this.shipmentForm.get('fromAddress') as FormGroup;
  }
  get parcel(): FormGroup {
    return this.shipmentForm.get('parcel') as FormGroup;
  }
  async handleSubmit() {
    if (this.shipmentForm.invalid) {
      return;
    }

    this.isLoading = true;
    const data = this.shipmentForm.value;

    try {
      const response = await fetch('http://127.0.0.1:5000/shipment_price', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const responseData = await response.json();
      console.log(responseData);
      this.rates = responseData;
      this.scrollToBottom();
    } catch (error: any) {
      console.error('Error:', error);
      window.alert(error.error);
    } finally {
      this.isLoading = false;
    }
  }

  scrollToBottom() {
    window.scrollTo(0, document.body.scrollHeight);
  }
}

<div class="App">
  <mat-card>
    <mat-card-content>
      <h2 class="page-title">Shipping Rates</h2>
      <form [formGroup]="shipmentForm">
        <!-- From Address -->
        <h3 class="section-title">From Address</h3>
        <!-- Pass the specific form group for fromAddress -->
        <app-address [addressComponents]="fromAddress"></app-address>

        <!-- To Address -->
        <h3 class="section-title">To Address</h3>
        <!-- Pass the specific form group for toAddress -->
        <app-address [addressComponents]="toAddress"></app-address>

        <!-- Parcel -->
        <h3 class="section-title">Parcel</h3>
        <!-- Pass the specific form group for parcel -->
        <app-parcel [parcel]="parcel"></app-parcel>

        <!-- Submit Button -->
        <button
          mat-raised-button
          color="primary"
          (click)="handleSubmit()"
          [disabled]="isLoading || shipmentForm.invalid"
        >
          Submit
        </button>
      </form>
    </mat-card-content>
  </mat-card>

  <!-- Shipping Rates -->
  <app-shipping-rates [rates]="rates"></app-shipping-rates>
</div>

// frontend-react/src/App.js
import React, { useEffect, useState } from 'react';
import './App.css';
import { Card, CardContent, Container, Grid, Typography, Button } from '@mui/material';
import Address from './components/Address';
import Parcel from './components/Parcel';
import ShippingRates from './components/ShippingRates';

function App() {
  const [fromAddress, setFromAddress] = useState({
    country: 'US',
    city: 'San Francisco',
    state: 'CA',
    zip: '94104',
    street1: '417 Montgomery St',
    street2: 'Floor 5',
    name: 'Hiro Protagonist',
    phone: '415-123-4567',
    email: 'example@example.com',
  });

  const [toAddress, setToAddress] = useState({
    country: 'US',
    city: 'New York',
    state: 'NY',
    zip: '10001',
    street1: '123 Broadway',
    name: 'John Doe',
    phone: '212-555-7890',
  });

  const [parcel, setParcel] = useState({});
  const [rates, setRates] = useState()
  const [isLoading, setLoading] = useState(false)

  const handleAddressComponentsChange = (addressType, addressData) => {
    if (addressType === 'from') {
      setFromAddress({ ...fromAddress, ...addressData });
    } else if (addressType === 'to') {
      setToAddress({ ...toAddress, ...addressData });
    }
  };

  const handleParcelChange = (parcelData) => {
    setParcel({ ...parcel, ...parcelData });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const data = {
      fromAddress,
      toAddress,
      parcel,
    };

    setLoading(true)
    try {
      const response = await fetch('http://127.0.0.1:5000/shipment_price', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      const responseData = await response.json();
      console.log(responseData);
      setRates(responseData);
    } catch (error) {
      console.error('Error:', error);
      window.alert(error.error);
    }
    setLoading(false)
  };
  const scrollToBottom = () => {
    window.scrollTo(0, document.body.scrollHeight);
  };

  useEffect(() => {
    if (rates && rates.length > 0) {
      scrollToBottom();
    }
  }, [rates]);
  return (
    <div className="App">
      <Container maxWidth="md" sx={{ mt: 4 }}>
        <Typography variant='h3' sx={{ my: 5 }}>Shipping Rates</Typography>
        <Grid container spacing={2} justifyContent="center">
          <Card variant="outlined">
            <CardContent>
              <form onSubmit={handleSubmit}>
                {/* From Address */}
                <Typography variant="h6">From Address</Typography>
                <Address
                  addressComponents={fromAddress}
                  handleAddressComponentsChange={(data) =>
                    handleAddressComponentsChange('from', data)
                  }
                />

                {/* To Address */}
                <Typography variant="h6" sx={{ mt: 4 }}>
                  To Address
                </Typography>
                <Address
                  addressComponents={toAddress}
                  handleAddressComponentsChange={(data) => handleAddressComponentsChange('to', data)}
                />

                {/* Parcel */}
                <Typography variant="h6" sx={{ mt: 4 }}>
                  Parcel
                </Typography>
                <Parcel parcel={parcel} handleParcelChange={handleParcelChange} />

                {/* Submit Button */}
                <br/>
                <Button variant="contained" color="primary" type='submit' disabled={isLoading}>
                  Submit
                </Button>
              </form>
            </CardContent>
          </Card>
          {
            rates != null && <ShippingRates rates={rates} />
          }
        </Grid>
      </Container>
    </div>
  );
}

export default App;
